version: '3.7'

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale
    volumes:
      - ./timescaledb-volume/:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
